"""join employee sector activity

Revision ID: 41a67eceefc9
Revises: 34e6756ee827
Create Date: 2025-01-03 01:09:24.751628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a67eceefc9'
down_revision = '34e6756ee827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector_activity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies_sector_of_activities', ['sector_activity_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sector_activity_id')

    # ### end Alembic commands ###
