"""join with companies employee

Revision ID: 100fcc525ebd
Revises: f24f00c91024
Create Date: 2025-01-03 00:48:57.194842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100fcc525ebd'
down_revision = 'f24f00c91024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies_companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
