"""unique name campaign

Revision ID: 2727ff7cba92
Revises: 3e655ea02fbc
Create Date: 2025-01-21 01:38:05.089447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2727ff7cba92'
down_revision = '3e655ea02fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_compaigns', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_compaigns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
