"""change companies field enseigne

Revision ID: 36552c2b3522
Revises: 84bbfe09fab9
Create Date: 2025-01-02 19:07:34.417665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36552c2b3522'
down_revision = '84bbfe09fab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_companies', schema=None) as batch_op:
        batch_op.drop_constraint('companies_companies_enseigne_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_companies', schema=None) as batch_op:
        batch_op.create_unique_constraint('companies_companies_enseigne_key', ['enseigne'])

    # ### end Alembic commands ###
