"""add path templates html and text

Revision ID: 3a7686e9b5e4
Revises: be0204363f2e
Create Date: 2025-01-21 01:14:34.684290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7686e9b5e4'
down_revision = 'be0204363f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_diffusions_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_html', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('template_text', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_diffusions_lists', schema=None) as batch_op:
        batch_op.drop_column('template_text')
        batch_op.drop_column('template_html')

    # ### end Alembic commands ###
