"""create email model and delete fields in diffusion_list model

Revision ID: 3e655ea02fbc
Revises: 3a7686e9b5e4
Create Date: 2025-01-21 01:23:51.920941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e655ea02fbc'
down_revision = '3a7686e9b5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_html', sa.String(), nullable=True),
    sa.Column('template_text', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_compaigns.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_diffusions_lists', schema=None) as batch_op:
        batch_op.drop_column('template_html')
        batch_op.drop_column('template_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_diffusions_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_text', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('template_html', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('marketing_emails')
    # ### end Alembic commands ###
