"""change companies field email

Revision ID: 84bbfe09fab9
Revises: d5e5e1b8e61f
Create Date: 2025-01-02 19:06:35.825531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84bbfe09fab9'
down_revision = 'd5e5e1b8e61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_companies', schema=None) as batch_op:
        batch_op.drop_constraint('companies_companies_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_companies', schema=None) as batch_op:
        batch_op.create_unique_constraint('companies_companies_email_key', ['email'])

    # ### end Alembic commands ###
