"""join employee civilities

Revision ID: 8d950b8bed7f
Revises: e52df9c39931
Create Date: 2025-01-03 01:03:32.979032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d950b8bed7f'
down_revision = 'e52df9c39931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('civility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies_civilities', ['civility_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('civility_id')

    # ### end Alembic commands ###
