"""add address field for company and employee model

Revision ID: a8a18705b048
Revises: 23fbe50bebfe
Create Date: 2025-01-06 16:07:13.257879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a18705b048'
down_revision = '23fbe50bebfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('companies_companies', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
