"""delete on cascade

Revision ID: e52df9c39931
Revises: 100fcc525ebd
Create Date: 2025-01-03 00:57:53.370334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52df9c39931'
down_revision = '100fcc525ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.drop_constraint('companies_employees_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies_companies', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('companies_employees_company_id_fkey', 'companies_companies', ['company_id'], ['id'])

    # ### end Alembic commands ###
